# Datos simulados de ocupación (Fase 1).
# Reemplazar por lecturas reales del servicio de visión artificial en fases futuras.
# El campo "status" NO se define aquí: se calcula en el service a partir de
# occupancyPercent, para que la regla de negocio viva en un solo lugar.

RAW_SPACES = [
    {
        "id": "biblioteca-fica",
        "name": "Biblioteca FICA",
        "description": "Biblioteca de la Facultad de Ingeniería, Ciencias Físicas y Matemática.",
        "type": "library",
        "building": "Facultad de Ingeniería",
        "floor": "Planta Baja",
        "totalSeats": 40,
        "occupiedSeats": 18,
        "freeSeats": 22,
        "computersTotal": 12,
        "computersAvailable": 5,
        "studyRoomsTotal": 3,
        "studyRoomsAvailable": 2,
        "distanceMinutes": 5,
        "occupancyPercent": 45,
        "latitude": -0.1995,
        "longitude": -78.5042,
    },
    {
        "id": "biblioteca-general",
        "name": "Biblioteca General",
        "description": "Biblioteca principal del Campus Central de la UCE.",
        "type": "library",
        "building": "Campus Central",
        "floor": "Planta 1",
        "totalSeats": 120,
        "occupiedSeats": 98,
        "freeSeats": 22,
        "computersTotal": 30,
        "computersAvailable": 4,
        "studyRoomsTotal": 8,
        "studyRoomsAvailable": 1,
        "distanceMinutes": 9,
        "occupancyPercent": 82,
        "latitude": -0.2012,
        "longitude": -78.5001,
    },
    {
        "id": "sala-grupal-2",
        "name": "Sala Grupal 2",
        "description": "Sala de estudio grupal en el Edificio A.",
        "type": "study_room",
        "building": "Edificio A",
        "floor": "Planta 1",
        "totalSeats": 8,
        "occupiedSeats": 2,
        "freeSeats": 6,
        "computersTotal": 0,
        "computersAvailable": 0,
        "studyRoomsTotal": 1,
        "studyRoomsAvailable": 1,
        "distanceMinutes": 3,
        "occupancyPercent": 25,
        "latitude": -0.1989,
        "longitude": -78.5030,
    },
    {
        "id": "laboratorio-computadoras",
        "name": "Laboratorio de Computadoras",
        "description": "Laboratorio de cómputo del Edificio Tecnológico.",
        "type": "computer_lab",
        "building": "Edificio Tecnológico",
        "floor": "Planta 2",
        "totalSeats": 30,
        "occupiedSeats": 29,
        "freeSeats": 1,
        "computersTotal": 30,
        "computersAvailable": 1,
        "studyRoomsTotal": 0,
        "studyRoomsAvailable": 0,
        "distanceMinutes": 7,
        "occupancyPercent": 97,
        "latitude": -0.2010,
        "longitude": -78.5015,
    },
    {
        "id": "sala-lectura-humanidades",
        "name": "Sala de Lectura Humanidades",
        "description": "Sala de lectura de la Facultad de Filosofía, Letras y Ciencias de la Educación.",
        "type": "study_room",
        "building": "Facultad de Filosofía",
        "floor": "Planta Baja",
        "totalSeats": 24,
        "occupiedSeats": 0,
        "freeSeats": 0,
        "computersTotal": 0,
        "computersAvailable": 0,
        "studyRoomsTotal": 2,
        "studyRoomsAvailable": 0,
        "distanceMinutes": 12,
        "occupancyPercent": None,
        "latitude": -0.2005,
        "longitude": -78.5025,
    },
]

# Nota (Fase 3): el mapeo espacio -> imagen/video de prueba (antes vivía aquí
# como SPACE_VISION_SOURCES) se movió a vision-service/app/space_registry.py,
# porque ahora es el vision-service quien analiza en segundo plano por su
# cuenta; el backend ya no construye ese payload ni llama a /vision/analyze.
